jenkins:
  systemMessage: "Master-Jenkins for CDEV team (poc testing): configured automatically with JCasC plugin\n\n"
plugins:
  required:
    git: 3.10.1
    pipeline-model-definition: 1.3.9
    pipeline-stage-step: 2.3
    pipeline-maven: 3.8.0
    workflow-aggregator: 2.6
    junit: 1.28
    docker-plugin:1.1.7
    kubernetes:1.17.2
    job-dsl:1.74
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "Maven 3"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.5.4"
jobs:
  - script: >
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/atrillanes1972/jcascmasterimage.git')
              }
          }
      }
    
  - script: >
      job("Seed_Job_test_POC") {
  
        parameters {
    
          stringParam("job_dsl_repo", "https://github.com/atrillanes1972/jcascmasterimage.git", "JOB DSL repo URI")
          stringParam("job_dsl_branch", "master", "Branch to process")
          stringParam("job_dsl_path", "jobs-for-seed/*.groovy", "Directory to process, and a glob for all groovy types")
        }
  
      scm {
    
        git {
      
          branch("\$job_dsl_branch")
          remote {
            name("origin")
            url("\$job_dsl_repo")
          }
        }
      }

      steps {
    
        dsl {
      
          external("\$job_dsl_path")
        }
      }
      }
