jenkins:
  systemMessage: "Master-Jenkins for CDEV team (poc testing): configured automatically with JCasC plugin\n\n"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "Maven 3"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.5.4"
jobs:
  - script: >
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }
  - script: >
      multibranchPipelineJob('configuration-as-code-sample2') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }
  - script: >
      job("Seed_Job_test_POC") {

  
        parameters {
    
          stringParam("job_dsl_repo", "", "Job DSL Repo")
          stringParam("job_dsl_branch", "", "Job DSL Branch")
          stringParam("job_dsl_path", "", "Location of Job DSL Groovy Script")
        }

  
      scm {
    
        git {
      
          branch("\$job_dsl_branch")
          remote {
            name("origin")
            url("\$job_dsl_repo")
          }
        }
      }

  
      steps {

    
        dsl {
      
          external("\$job_dsl_path")
        }
      }
}
